### ISSUE TITLE
IPromise#then signature fix

### ISSUE THREAD

**Issue by KirillGrishin** [cmichaelgraham/aurelia-typescript#13]
Hi.

I think the signature for this https://github.com/cmichaelgraham/aurelia-typescript/blob/master/skel-nav-esri-vs-ts/skel-nav-esri-vs-ts/typings/aurelia/aurelia.d.ts#L184 method should be something like the following.

```TypeScript
interface IPromise<T> {
    then<U>(callback: (response: T) => U): IPromise<U>;
}
```

I have [converted](https://github.com/Enrapt/aurelia-skeleton-navigation-gulp-typescript/tree/master/src/test/unit) tests to TypeScript / Gulp and I used your aurelia.d.ts. With the current implementation the compiler would give the error.

```shell
src/test/unit/flickr.spec.ts(26,20): 2339 Property 'then' does not exist on type 'void'
```

Unfortunately I do not have Visual Studio, so I cannot check it against your repository. That's why I am raising this as an issue rather than a pull request.

Cheers.

**Comment by cmichaelgraham** [comment]
Thanks @KirillGrishin !! :)  I'll put that in and run it through its paces.  I really appreciate the input :)

**Comment by cmichaelgraham** [comment]
aurelia.d.ts updated with proposed change.  smoke tests completed on each sample.

thanks again @KirillGrishin !!
