### ISSUE TITLE
aurelia.d.ts change for framework/logging (LogManager) relationship

### ISSUE THREAD

**Issue by michaelsg** [cmichaelgraham/aurelia-typescript#15]
Is there a master aurelia.d.ts against which you would like a PR? Or I could put my changes into one of the VS/TS solutions (skel?) and share it that way.

I see you are trying a process to generate the file - so are manual updates even something you are interested in?

**Comment by cmichaelgraham** [comment]
hi @michaelsg - definitely interested in manual updates while we figure out the automated process.

for the PR, you can modify the [aurelia.d.ts](https://github.com/cmichaelgraham/aurelia-typescript/blob/master/aurelia.d.ts) in the root folder of the repo.  i'll copy it into each of the samples as i test them out with the changes :smile:

**Comment by michaelsg** [comment]
It seems I actually started with aurelia-mod.d.ts. It was newer and seemed to be more complete - right after the 0.10.0 release. PR that one or the original?

**Comment by cmichaelgraham** [comment]
can you PR the original and include the updates from aurelia-mod.d.ts?
