### ISSUE TITLE
pwkad-aurelia-samples in Visual Studio 2013 does just not start/it hangs

### ISSUE THREAD

**Issue by bastienJS** [cmichaelgraham/aurelia-typescript#17]
I run VS2013 with update 4 and the Typescript 1.4 for VS 2013.

I rebuild the solution without errors and start the project with chrome.

But nothing starts... instead it hangs in VS2013.

**Comment by bastienJS** [comment]
haha... I had to restart my PC to make it work...

**Comment by cmichaelgraham** [comment]
glad you got it working !! :+1: 

let me know if you have any other troubles or questions / comments :)
