### ISSUE TITLE
Problem with aurelia-require-bundle: no such file or directory sightglass.js

### ISSUE THREAD

**Issue by pszybiak** [cmichaelgraham/aurelia-typescript#28]
Hi
I have a problem with aurelia-require-bundle.
When I run

`node r.js -o name=aurelia-bundle-manifest baseUrl=. mainConfigFile=main-config.js out=aurelia-bundle.js optimize=none`

I get exception:

`Tracing dependencies for: aurelia-bundle-manifest
Error: ENOENT, no such file or directory 'F:\aurelia\aurelia-typescript\aurelia-require-bundle\sightglass.js'
In module tree:
 aurelia-bundle-manifest
   aurelia-loader/index
     aurelia-loader/loader
       core-js/core.src`

I'm new to all of this code (aurelia, TS, requirejs) and I don't know where I've made a mistake.
I think core.src.js file is a bundle and have inside core.js, sightglass.js and rivets.patched.js
I don't know what and why is looking for sightglass.js file.
When I put sightglass.js file to my base directory then node r.js command is OK, but file aurelia-bundle.js has duplicated sightglass.js code.

**Comment by cmichaelgraham** [comment]
can you post your aurelia-bundle-manifest here?  (let me know if you need help posting it)

**Comment by pszybiak** [comment]
I didn't change anything in your code. I downloaded the repo and tried to run all steps described
here: https://github.com/cmichaelgraham/aurelia-typescript/tree/master/aurelia-require-bundle

aurelia-bundle-manifest is the same as https://github.com/cmichaelgraham/aurelia-typescript/blob/master/aurelia-require-bundle/aurelia-bundle-manifest.js

**Comment by cmichaelgraham** [comment]
gotcha - i think the issue has to do with changes in core-js.  

i'm working on porting the [samples to typescript 1.5 beta](https://github.com/cmichaelgraham/aurelia-typescript/tree/typescript-1-5-port).  

i have been using a [bundling repo](https://github.com/cmichaelgraham/aurelia-amd-bundler) to create the bundles for that

things should be more stable in a week or so, but you can try the above bundling repo and see if you get better results.

the bundling repo uses the latest aurelia libraries and typescript 1.5 beta.  good because its current, bad because its cutting edge (unless you're like me and like that sort of thing :+1: )

**Comment by pszybiak** [comment]
Thanks. I'll try aurelia-amd-bundler.
And yes, I'm like you and I like beta versions :+1:

**Comment by cmichaelgraham** [comment]
awesome !!

**Comment by cmichaelgraham** [comment]
can i ask you what you see if you go to this url?
https://github.com/cmichaelgraham/aurelia-typescript/tree/typescript-1-5-port/code-sandbox/code-sandbox/views#boards

that is a board showing the tasks and there status in the pipeline using [zenhub](https://www.zenhub.io/)

not sure what you see if you don't install their chrome extension

**Comment by pszybiak** [comment]
I see just files in `views` catalog.

**Comment by cmichaelgraham** [comment]
ok cool :sunglasses:

**Comment by luboid** [comment]
Hi,

Is this possible, not to include core-js into bundle, because - if we are using IE10 there is need to include it as script tag (I think this extend global)

It is simple to load it by configuring requirejs

```
{
    paths: {
        corejs: '/scripts/core-js/'
    },
    shim: {
        'corejs/core': {
            exports : window.core
        }
    },
    map: {
        '*': {
            'core-js': 'corejs/core'
        }
    }
}
```

**Comment by luboid** [comment]
Hi,

Is this possible, not to include core-js into bundle, because if we are using IE10 there is need to include it as script tag, it can be easily loaded through requirejs configuration
