### ISSUE TITLE
d.ts typings error on compile

### ISSUE THREAD

**Issue by delebash** [cmichaelgraham/aurelia-typescript#41]
Windows 7 x64
Typescript Beta 1.5
Phpstorm 9 EAP via gulp-typescript

getting typings\aurelia\aurelia-templating.d.ts(76,1): error TS1128: Declaration or statement expected.

Just this 1 error on compile, using current master branch mater folder/typings d.ts files https://github.com/cmichaelgraham/aurelia-typescript/tree/master/master/typings

**Comment by cmichaelgraham** [comment]
thanks for the heads up - i'll take a look...  seems like there was an extra right curly bracket.  can you retest with the edit i made?

**Comment by delebash** [comment]
fixed thanks
